workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: 3.16.5  # Use specific Flutter version with Dart 3.16.5
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
